#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

    #include "ast.h"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include "symbol_table.h"

    AST* make_node(char* name, int count, ...);
    void print_ast(AST* node, int indent);
    void yyerror(const char* s);
    void print_symbol_tables();
    int yylex();
    int yydebug = 1;
    int inside_main = 0;
    int scope_parent[100] = {-1};  
    int function_scopes[100] = {0}; 
    int current_function = 0; 
    int main_defined = 0;  
    extern int preserve_symbol_tables;
    // Add to your globals in parser.y
    char current_function_name[256] = "";
    int current_param_index = 0;

#line 25 "parser.y"
typedef union {
    struct ast_node* ast ;
    char* sval;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	OR	258
#define	AND	259
#define	PLUS	260
#define	MINUS	261
#define	MULT	262
#define	DIV	263
#define	EQ	264
#define	NE	265
#define	GT	266
#define	GE	267
#define	LT	268
#define	LE	269
#define	NOT	270
#define	ID	271
#define	CHAR_LITERAL	272
#define	STRING_LITERAL	273
#define	NUM	274
#define	TRUE	275
#define	FALSE	276
#define	TYPE_INT	277
#define	TYPE_CHAR	278
#define	TYPE_REAL	279
#define	TYPE_BOOL	280
#define	TYPE_STRING	281
#define	TYPE_INT_PTR	282
#define	TYPE_CHAR_PTR	283
#define	TYPE_REAL_PTR	284
#define	DEF	285
#define	T_BEGIN	286
#define	T_END	287
#define	IF	288
#define	ELSE	289
#define	ELIF	290
#define	WHILE	291
#define	FOR	292
#define	DO	293
#define	CALL	294
#define	RETURN	295
#define	RETURNS	296
#define	VAR	297
#define	NULLPTR	298
#define	ASSIGN	299
#define	ADDRESS	300
#define	COLON	301
#define	SEMICOLON	302
#define	COMMA	303
#define	LPAREN	304
#define	RPAREN	305
#define	LBRACK	306
#define	RBRACK	307
#define	BAR	308
#define	TYPE	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int OR;
static const int AND;
static const int PLUS;
static const int MINUS;
static const int MULT;
static const int DIV;
static const int EQ;
static const int NE;
static const int GT;
static const int GE;
static const int LT;
static const int LE;
static const int NOT;
static const int ID;
static const int CHAR_LITERAL;
static const int STRING_LITERAL;
static const int NUM;
static const int TRUE;
static const int FALSE;
static const int TYPE_INT;
static const int TYPE_CHAR;
static const int TYPE_REAL;
static const int TYPE_BOOL;
static const int TYPE_STRING;
static const int TYPE_INT_PTR;
static const int TYPE_CHAR_PTR;
static const int TYPE_REAL_PTR;
static const int DEF;
static const int T_BEGIN;
static const int T_END;
static const int IF;
static const int ELSE;
static const int ELIF;
static const int WHILE;
static const int FOR;
static const int DO;
static const int CALL;
static const int RETURN;
static const int RETURNS;
static const int VAR;
static const int NULLPTR;
static const int ASSIGN;
static const int ADDRESS;
static const int COLON;
static const int SEMICOLON;
static const int COMMA;
static const int LPAREN;
static const int RPAREN;
static const int LBRACK;
static const int RBRACK;
static const int BAR;
static const int TYPE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,OR=258
	,AND=259
	,PLUS=260
	,MINUS=261
	,MULT=262
	,DIV=263
	,EQ=264
	,NE=265
	,GT=266
	,GE=267
	,LT=268
	,LE=269
	,NOT=270
	,ID=271
	,CHAR_LITERAL=272
	,STRING_LITERAL=273
	,NUM=274
	,TRUE=275
	,FALSE=276
	,TYPE_INT=277
	,TYPE_CHAR=278
	,TYPE_REAL=279
	,TYPE_BOOL=280
	,TYPE_STRING=281
	,TYPE_INT_PTR=282
	,TYPE_CHAR_PTR=283
	,TYPE_REAL_PTR=284
	,DEF=285
	,T_BEGIN=286
	,T_END=287
	,IF=288
	,ELSE=289
	,ELIF=290
	,WHILE=291
	,FOR=292
	,DO=293
	,CALL=294
	,RETURN=295
	,RETURNS=296
	,VAR=297
	,NULLPTR=298
	,ASSIGN=299
	,ADDRESS=300
	,COLON=301
	,SEMICOLON=302
	,COMMA=303
	,LPAREN=304
	,RPAREN=305
	,LBRACK=306
	,RBRACK=307
	,BAR=308
	,TYPE=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::OR=258;
const int YY_parse_CLASS::AND=259;
const int YY_parse_CLASS::PLUS=260;
const int YY_parse_CLASS::MINUS=261;
const int YY_parse_CLASS::MULT=262;
const int YY_parse_CLASS::DIV=263;
const int YY_parse_CLASS::EQ=264;
const int YY_parse_CLASS::NE=265;
const int YY_parse_CLASS::GT=266;
const int YY_parse_CLASS::GE=267;
const int YY_parse_CLASS::LT=268;
const int YY_parse_CLASS::LE=269;
const int YY_parse_CLASS::NOT=270;
const int YY_parse_CLASS::ID=271;
const int YY_parse_CLASS::CHAR_LITERAL=272;
const int YY_parse_CLASS::STRING_LITERAL=273;
const int YY_parse_CLASS::NUM=274;
const int YY_parse_CLASS::TRUE=275;
const int YY_parse_CLASS::FALSE=276;
const int YY_parse_CLASS::TYPE_INT=277;
const int YY_parse_CLASS::TYPE_CHAR=278;
const int YY_parse_CLASS::TYPE_REAL=279;
const int YY_parse_CLASS::TYPE_BOOL=280;
const int YY_parse_CLASS::TYPE_STRING=281;
const int YY_parse_CLASS::TYPE_INT_PTR=282;
const int YY_parse_CLASS::TYPE_CHAR_PTR=283;
const int YY_parse_CLASS::TYPE_REAL_PTR=284;
const int YY_parse_CLASS::DEF=285;
const int YY_parse_CLASS::T_BEGIN=286;
const int YY_parse_CLASS::T_END=287;
const int YY_parse_CLASS::IF=288;
const int YY_parse_CLASS::ELSE=289;
const int YY_parse_CLASS::ELIF=290;
const int YY_parse_CLASS::WHILE=291;
const int YY_parse_CLASS::FOR=292;
const int YY_parse_CLASS::DO=293;
const int YY_parse_CLASS::CALL=294;
const int YY_parse_CLASS::RETURN=295;
const int YY_parse_CLASS::RETURNS=296;
const int YY_parse_CLASS::VAR=297;
const int YY_parse_CLASS::NULLPTR=298;
const int YY_parse_CLASS::ASSIGN=299;
const int YY_parse_CLASS::ADDRESS=300;
const int YY_parse_CLASS::COLON=301;
const int YY_parse_CLASS::SEMICOLON=302;
const int YY_parse_CLASS::COMMA=303;
const int YY_parse_CLASS::LPAREN=304;
const int YY_parse_CLASS::RPAREN=305;
const int YY_parse_CLASS::LBRACK=306;
const int YY_parse_CLASS::RBRACK=307;
const int YY_parse_CLASS::BAR=308;
const int YY_parse_CLASS::TYPE=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		280
#define	YYFLAG		-32768
#define	YYNTBASE	55

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 87)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     7,     9,    10,    21,    22,    32,    33,
    42,    43,    51,    53,    54,    58,    60,    65,    67,    69,
    71,    73,    75,    77,    79,    81,    84,    86,    88,    90,
    92,    94,    96,    98,   100,   102,   104,   106,   108,   110,
   115,   123,   129,   133,   137,   140,   142,   148,   154,   160,
   166,   172,   180,   188,   196,   204,   212,   220,   229,   235,
   241,   247,   251,   254,   262,   267,   272,   280,   289,   294,
   300,   305,   310,   315,   322,   329,   336,   346,   356,   360,
   362,   364,   365,   369,   371,   380,   387,   388,   393,   394,
   398,   402,   406,   410,   414,   418,   422,   426,   430,   434,
   438,   442,   447,   451,   453,   455,   457,   459,   461,   463,
   465,   467,   469,   471,   477,   482,   486,   490,   493,   496
};

static const short yyrhs[] = {    56,
     0,     1,     0,    56,    57,     0,    57,     0,     0,    30,
    16,    49,    62,    50,    46,    41,    65,    58,    66,     0,
     0,    30,    16,    49,    50,    46,    41,    65,    59,    66,
     0,     0,    30,    16,    49,    62,    50,    46,    60,    66,
     0,     0,    30,    16,    49,    50,    46,    61,    66,     0,
    63,     0,     0,    63,    47,    64,     0,    64,     0,    16,
    65,    46,    16,     0,    22,     0,    23,     0,    24,     0,
    25,     0,    26,     0,    27,     0,    28,     0,    29,     0,
    66,    67,     0,    67,     0,    68,     0,    73,     0,    72,
     0,    83,     0,    75,     0,    77,     0,    79,     0,    76,
     0,    69,     0,    82,     0,    81,     0,    56,     0,    16,
    44,    86,    47,     0,    16,    51,    86,    52,    44,    86,
    47,     0,     7,    16,    44,    86,    47,     0,    42,    70,
    83,     0,    42,    70,    67,     0,    70,    71,     0,    71,
     0,    54,    22,    46,    16,    47,     0,    54,    25,    46,
    16,    47,     0,    54,    23,    46,    16,    47,     0,    54,
    26,    46,    16,    47,     0,    54,    24,    46,    16,    47,
     0,    54,    24,    46,    16,    46,    19,    47,     0,    54,
    22,    46,    16,    46,    19,    47,     0,    54,    23,    46,
    16,    46,    17,    47,     0,    54,    26,    46,    16,    46,
    18,    47,     0,    54,    25,    46,    16,    46,    20,    47,
     0,    54,    25,    46,    16,    46,    21,    47,     0,    54,
    26,    46,    16,    51,    19,    52,    47,     0,    54,    27,
    46,    16,    47,     0,    54,    28,    46,    16,    47,     0,
    54,    29,    46,    16,    47,     0,    40,    86,    47,     0,
    40,    47,     0,    33,    86,    46,    83,    34,    46,    83,
     0,    33,    86,    46,    83,     0,    33,    86,    46,    67,
     0,    33,    86,    46,    67,    34,    46,    67,     0,    33,
    86,    46,    83,    74,    34,    46,    83,     0,    35,    86,
    46,    83,     0,    74,    35,    86,    46,    83,     0,    36,
    46,    86,    47,     0,    36,    86,    46,    83,     0,    36,
    86,    46,    67,     0,    38,    46,    66,    36,    86,    47,
     0,    38,    46,    67,    36,    86,    47,     0,    38,    46,
    83,    36,    86,    47,     0,    37,    49,    68,    86,    47,
    78,    50,    46,    83,     0,    37,    49,    68,    86,    47,
    78,    50,    46,    67,     0,    16,    44,    86,     0,    86,
     0,    80,     0,     0,    80,    48,    86,     0,    86,     0,
    16,    44,    39,    16,    49,    79,    50,    47,     0,    39,
    16,    49,    79,    50,    47,     0,     0,    31,    84,    66,
    32,     0,     0,    31,    85,    32,     0,    86,     5,    86,
     0,    86,     6,    86,     0,    86,     7,    86,     0,    86,
     8,    86,     0,    86,     9,    86,     0,    86,    10,    86,
     0,    86,    13,    86,     0,    86,    11,    86,     0,    86,
    14,    86,     0,    86,    12,    86,     0,    49,    86,    50,
     0,    16,    51,    86,    52,     0,    51,    86,    52,     0,
    19,     0,    16,     0,    17,     0,    18,     0,    43,     0,
    20,     0,    21,     0,     4,     0,     3,     0,    15,     0,
    39,    16,    49,    79,    50,     0,    16,    49,    79,    50,
     0,    86,     4,    86,     0,    86,     3,    86,     0,    15,
    86,     0,     7,    16,     0,    45,    16,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    53,    57,    62,    64,    66,    99,   110,   135,   146,   171,
   182,   201,   214,   216,   219,   223,   229,   245,   247,   248,
   249,   250,   251,   252,   253,   256,   261,   267,   269,   270,
   271,   272,   273,   274,   275,   276,   277,   278,   279,   282,
   313,   340,   375,   379,   383,   387,   391,   396,   400,   404,
   408,   412,   416,   420,   424,   428,   432,   436,   446,   450,
   454,   461,   473,   483,   489,   494,   499,   504,   512,   518,
   524,   530,   535,   541,   546,   551,   558,   563,   570,   574,
   578,   580,   583,   588,   595,   625,   653,   657,   661,   664,
   670,   682,   693,   704,   715,   726,   737,   748,   759,   770,
   781,   784,   804,   812,   813,   822,   823,   824,   825,   826,
   827,   828,   829,   830,   842,   854,   855,   856,   859,   877
};

static const char * const yytname[] = {   "$","error","$illegal.","OR","AND",
"PLUS","MINUS","MULT","DIV","EQ","NE","GT","GE","LT","LE","NOT","ID","CHAR_LITERAL",
"STRING_LITERAL","NUM","TRUE","FALSE","TYPE_INT","TYPE_CHAR","TYPE_REAL","TYPE_BOOL",
"TYPE_STRING","TYPE_INT_PTR","TYPE_CHAR_PTR","TYPE_REAL_PTR","DEF","T_BEGIN",
"T_END","IF","ELSE","ELIF","WHILE","FOR","DO","CALL","RETURN","RETURNS","VAR",
"NULLPTR","ASSIGN","ADDRESS","COLON","SEMICOLON","COMMA","LPAREN","RPAREN","LBRACK",
"RBRACK","BAR","TYPE","program","func_list","function","@1","@2","@3","@4","par_list",
"param_list_item_list","par_list_item","type","stmt_list","stmt","assignment",
"var_stmt","type_decls","type_decl","return_stmt","if_stmt","elif_list","while_stmt",
"do_while_stmt","for_stmt","update_expr","call_args","call_list","assignment_call",
"void_call","block","@5","@6","expr",""
};
#endif

static const short yyr1[] = {     0,
    55,    55,    56,    56,    58,    57,    59,    57,    60,    57,
    61,    57,    62,    62,    63,    63,    64,    65,    65,    65,
    65,    65,    65,    65,    65,    66,    66,    67,    67,    67,
    67,    67,    67,    67,    67,    67,    67,    67,    67,    68,
    68,    68,    69,    69,    70,    70,    71,    71,    71,    71,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    72,    72,    73,    73,    73,    73,    73,    74,    74,
    75,    75,    75,    76,    76,    76,    77,    77,    78,    78,
    79,    79,    80,    80,    81,    82,    84,    83,    85,    83,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86,
    86,    86,    86,    86,    86,    86,    86,    86,    86,    86
};

static const short yyr2[] = {     0,
     1,     1,     2,     1,     0,    10,     0,     9,     0,     8,
     0,     7,     1,     0,     3,     1,     4,     1,     1,     1,
     1,     1,     1,     1,     1,     2,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     4,
     7,     5,     3,     3,     2,     1,     5,     5,     5,     5,
     5,     7,     7,     7,     7,     7,     7,     8,     5,     5,
     5,     3,     2,     7,     4,     4,     7,     8,     4,     5,
     4,     4,     4,     6,     6,     6,     9,     9,     3,     1,
     1,     0,     3,     1,     8,     6,     0,     4,     0,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     4,     3,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     5,     4,     3,     3,     2,     2,     2
};

static const short yydefact[] = {     0,
     2,     0,     1,     4,     0,     3,     0,     0,     0,     0,
    13,    16,    18,    19,    20,    21,    22,    23,    24,    25,
     0,    11,     0,     0,     0,     0,    82,     9,    15,    17,
     7,   112,   111,     0,   113,   105,   106,   107,   104,   109,
   110,    87,     0,     0,     0,     0,     0,     0,     0,   108,
     0,     0,     0,    39,    12,    27,    28,    36,    30,    29,
    32,    35,    33,    34,    81,    38,    37,    31,    84,     0,
    82,    82,   119,     0,   105,     0,   118,     0,    82,     0,
    82,     0,     0,     0,     0,     0,     0,     0,    63,     0,
     0,    82,    46,   120,     0,     0,    26,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     5,    10,     8,     0,   119,     0,     0,     0,     0,     0,
     0,     0,    90,    82,     0,    82,     0,     0,     0,     0,
    27,    31,    82,    62,     0,     0,     0,     0,     0,     0,
     0,     0,    44,    45,    31,   101,   103,    83,   117,   116,
    91,    92,    93,    94,    95,    96,    98,   100,    97,    99,
    82,     0,     0,    82,     0,    40,   115,   102,    88,    66,
    31,    71,    73,    31,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     6,    42,   102,     0,    82,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   114,     0,     0,     0,     0,
     0,     0,     0,     0,   114,     0,     0,    82,     0,     0,
     0,     0,     0,   105,     0,    80,    74,    75,    76,    86,
     0,    47,     0,    49,     0,    51,     0,    48,     0,    50,
     0,    59,    60,    61,   114,    41,    67,    64,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    85,    69,    68,     0,    79,    82,    53,    54,    52,    56,
    57,    55,     0,    70,    78,    31,    58,     0,     0,     0
};

static const short yydefgoto[] = {   278,
    54,     4,   161,    72,    71,    27,    10,    11,    12,    21,
    55,    97,    57,    58,    92,    93,    59,    60,   200,    61,
    62,    63,   225,    64,    65,    66,    67,    68,    81,    82,
    69
};

static const short yypact[] = {     9,
-32768,     0,    -8,-32768,    18,-32768,    -9,   417,    11,    36,
    41,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    37,    49,    50,    82,    87,   417,   310,    77,-32768,-32768,
-32768,-32768,-32768,   103,   754,   -31,-32768,-32768,-32768,-32768,
-32768,-32768,   416,   360,    84,   123,   133,   409,   110,-32768,
   158,   416,   416,    -8,   310,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   128,-32768,-32768,-32768,   803,   417,
   310,   310,   134,   161,    33,   163,-32768,   459,   416,   416,
   310,   160,    22,   416,   722,     5,   310,   141,-32768,   527,
   467,   168,-32768,-32768,   118,   101,-32768,   416,   416,   416,
   416,   416,   416,   416,   416,   416,   416,   416,   416,   416,
-32768,   310,   310,   416,-32768,   416,   145,   165,   539,   146,
   221,   267,-32768,   310,   584,   310,   179,     8,   416,   353,
   164,   166,   416,-32768,   151,   157,   169,   170,   172,   174,
   175,   190,-32768,-32768,-32768,-32768,-32768,   803,   132,   149,
   325,   325,   255,   255,-32768,-32768,-32768,-32768,-32768,-32768,
   310,   596,   237,   416,   188,-32768,-32768,   194,-32768,   178,
     3,-32768,-32768,-32768,   134,   416,   416,   608,   360,   416,
   416,   159,   198,   256,   259,   260,   261,   262,   263,   264,
   310,-32768,-32768,   231,   416,   416,   244,   245,   416,    12,
   249,   466,   515,   653,   665,   246,    17,    46,    48,    55,
    15,   247,   248,   268,-32768,   242,   677,   310,   265,   734,
   273,   416,   194,    -1,   252,   803,-32768,-32768,-32768,-32768,
   289,-32768,   294,-32768,   301,-32768,    96,-32768,   303,-32768,
   304,-32768,-32768,-32768,   275,-32768,-32768,-32768,   265,   265,
   746,   416,   278,   295,   297,   298,   307,   311,   315,   299,
-32768,-32768,-32768,   265,   803,   310,-32768,-32768,-32768,-32768,
-32768,-32768,   318,-32768,-32768,-32768,-32768,   366,   382,-32768
};

static const short yypgoto[] = {-32768,
   385,     2,-32768,-32768,-32768,-32768,-32768,-32768,   363,   -17,
   -70,   -27,   302,-32768,-32768,   305,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   -75,-32768,-32768,-32768,   -84,-32768,-32768,
   -29
};


#define	YYLAST		817


static const short yytable[] = {    56,
   112,   113,   132,   120,     6,    77,     8,   145,    31,     1,
   122,   127,    78,    83,    85,     5,   130,    79,    90,    80,
   128,     2,    95,    96,    99,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   198,   199,     2,   171,
     9,   174,   252,    56,    56,   221,   222,    79,   119,   116,
   121,   176,   111,    56,   125,     6,    22,   182,   177,   131,
   239,   240,   231,   232,   143,   241,     7,   124,   148,   149,
   150,   151,   152,   153,   154,   155,   156,   157,   158,   159,
   160,    79,    25,   116,   162,    23,   163,    24,   194,    26,
   191,   233,   234,   235,   236,    28,   170,     8,   173,   178,
   237,   238,    30,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   257,   258,    70,    73,   216,
    99,   100,   101,   102,   103,   104,   105,   106,   107,   108,
   109,   110,    86,    56,   248,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,   119,   201,    88,   203,
   204,   205,   147,   101,   102,   103,   104,   105,   106,   107,
   108,   109,   110,    91,   262,   263,   217,   146,    87,   220,
    32,    33,   226,    94,    34,    98,   115,   114,   117,   274,
   165,   276,    35,    36,    37,    38,    39,    40,    41,   133,
   247,   123,   251,   164,   175,   167,   183,     2,    42,   180,
    43,   181,   184,    44,    45,    46,    47,    48,   206,    49,
    50,   197,    51,   207,   185,   186,    52,   187,    53,   188,
   189,    91,   265,    99,   100,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   190,   195,   196,   275,    99,
   100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
   110,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,   109,   110,   105,   106,   107,   108,   109,   110,    32,
    33,   208,   168,    34,   209,   210,   211,   212,   213,   214,
   215,    35,    36,    37,    38,    39,    40,    41,   193,   218,
   219,   245,   230,   242,   243,    42,     2,    42,   169,    43,
   223,   253,    44,    45,    46,    47,    48,   254,    49,    50,
   255,    51,    32,    33,   244,    52,    34,    53,   250,   256,
   259,   261,   260,   266,    35,    36,    37,    38,    39,    40,
    41,   103,   104,   105,   106,   107,   108,   109,   110,     2,
    42,   267,    43,   268,   269,    44,    45,    46,    47,    48,
   273,    49,    50,   270,    51,    32,    33,   271,    52,    34,
    53,   272,    32,    33,   277,   279,    74,    35,    36,    37,
    38,    39,    40,    41,    35,    75,    37,    38,    39,    40,
    41,   280,     2,    42,     3,    43,    29,   129,   179,    45,
    46,    47,    48,     0,    49,    50,   144,    51,    76,     0,
     0,    52,    50,    53,    51,    84,     0,     0,    52,     0,
    53,    32,    33,     0,     0,    74,     0,     0,    32,    33,
     0,     0,    74,    35,    75,    37,    38,    39,    40,    41,
    35,    75,    37,    38,    39,    40,    41,     0,    13,    14,
    15,    16,    17,    18,    19,    20,     0,    76,     0,     0,
     0,    50,     0,    51,    76,    89,     0,    52,    50,    53,
    51,    32,    33,     0,    52,    74,    53,     0,    32,    33,
     0,     0,    74,    35,    75,    37,    38,    39,    40,    41,
    35,   224,    37,    38,    39,    40,    41,     0,   135,   136,
   137,   138,   139,   140,   141,   142,     0,   118,     0,     0,
     0,    50,     0,    51,    76,     0,     0,    52,    50,    53,
    51,     0,     0,     0,    52,     0,    53,    99,   100,   101,
   102,   103,   104,   105,   106,   107,   108,   109,   110,    99,
   100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
   110,    99,   100,   101,   102,   103,   104,   105,   106,   107,
   108,   109,   110,     0,     0,     0,     0,     0,     0,     0,
   126,   227,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   134,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   166,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,   109,   110,    99,   100,
   101,   102,   103,   104,   105,   106,   107,   108,   109,   110,
    99,   100,   101,   102,   103,   104,   105,   106,   107,   108,
   109,   110,     0,     0,     0,     0,     0,     0,     0,     0,
   172,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,   192,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   202,    99,   100,   101,   102,   103,
   104,   105,   106,   107,   108,   109,   110,    99,   100,   101,
   102,   103,   104,   105,   106,   107,   108,   109,   110,    99,
   100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
   110,     0,     0,     0,     0,     0,     0,     0,     0,   228,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,   229,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,   246,    99,   100,   101,   102,   103,   104,
   105,   106,   107,   108,   109,   110,    99,   100,   101,   102,
   103,   104,   105,   106,   107,   108,   109,   110,    99,   100,
   101,   102,   103,   104,   105,   106,   107,   108,   109,   110,
     0,     0,     0,     0,     0,     0,     0,   126,    35,    75,
    37,    38,    39,    40,    41,     0,     0,     0,     0,   249,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,   264,    76,     0,     0,     0,    50,     0,    51,     0,
     0,     0,    52,     0,    53,    99,   100,   101,   102,   103,
   104,   105,   106,   107,   108,   109,   110
};

static const short yycheck[] = {    27,
    71,    72,    87,    79,     3,    35,    16,    92,    26,     1,
    81,     7,    44,    43,    44,    16,    87,    49,    48,    51,
    16,    30,    52,    53,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,    34,    35,    30,   124,
    50,   126,    44,    71,    72,    34,    35,    49,    78,    51,
    80,    44,    70,    81,    84,    54,    46,   133,    51,    87,
    46,    47,    46,    47,    92,    51,    49,    46,    98,    99,
   100,   101,   102,   103,   104,   105,   106,   107,   108,   109,
   110,    49,    46,    51,   114,    50,   116,    47,   164,    41,
   161,    46,    47,    46,    47,    46,   124,    16,   126,   129,
    46,    47,    16,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    20,    21,    41,    16,   195,
     3,     4,     5,     6,     7,     8,     9,    10,    11,    12,
    13,    14,    49,   161,   219,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,   176,   177,    16,   179,
   180,   181,    52,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,    54,   249,   250,   196,    50,    46,   199,
     3,     4,   202,    16,     7,    48,    16,    44,    16,   264,
    16,   266,    15,    16,    17,    18,    19,    20,    21,    49,
   218,    32,   222,    49,    16,    50,    46,    30,    31,    36,
    33,    36,    46,    36,    37,    38,    39,    40,    50,    42,
    43,    34,    45,    16,    46,    46,    49,    46,    51,    46,
    46,    54,   252,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,    13,    14,    46,    49,    44,   266,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,     9,    10,    11,    12,    13,    14,     3,
     4,    16,    52,     7,    16,    16,    16,    16,    16,    16,
    50,    15,    16,    17,    18,    19,    20,    21,    52,    46,
    46,    50,    47,    47,    47,    31,    30,    31,    32,    33,
    52,    50,    36,    37,    38,    39,    40,    19,    42,    43,
    17,    45,     3,     4,    47,    49,     7,    51,    46,    19,
    18,    47,    19,    46,    15,    16,    17,    18,    19,    20,
    21,     7,     8,     9,    10,    11,    12,    13,    14,    30,
    31,    47,    33,    47,    47,    36,    37,    38,    39,    40,
    52,    42,    43,    47,    45,     3,     4,    47,    49,     7,
    51,    47,     3,     4,    47,     0,     7,    15,    16,    17,
    18,    19,    20,    21,    15,    16,    17,    18,    19,    20,
    21,     0,    30,    31,     0,    33,    24,    86,    36,    37,
    38,    39,    40,    -1,    42,    43,    92,    45,    39,    -1,
    -1,    49,    43,    51,    45,    46,    -1,    -1,    49,    -1,
    51,     3,     4,    -1,    -1,     7,    -1,    -1,     3,     4,
    -1,    -1,     7,    15,    16,    17,    18,    19,    20,    21,
    15,    16,    17,    18,    19,    20,    21,    -1,    22,    23,
    24,    25,    26,    27,    28,    29,    -1,    39,    -1,    -1,
    -1,    43,    -1,    45,    39,    47,    -1,    49,    43,    51,
    45,     3,     4,    -1,    49,     7,    51,    -1,     3,     4,
    -1,    -1,     7,    15,    16,    17,    18,    19,    20,    21,
    15,    16,    17,    18,    19,    20,    21,    -1,    22,    23,
    24,    25,    26,    27,    28,    29,    -1,    39,    -1,    -1,
    -1,    43,    -1,    45,    39,    -1,    -1,    49,    43,    51,
    45,    -1,    -1,    -1,    49,    -1,    51,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    46,    47,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    47,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    47,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
     3,     4,     5,     6,     7,     8,     9,    10,    11,    12,
    13,    14,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    47,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    47,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    47,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    13,    14,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    47,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    47,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    47,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,     3,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,     3,     4,
     5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    46,    15,    16,
    17,    18,    19,    20,    21,    -1,    -1,    -1,    -1,    46,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    46,    39,    -1,    -1,    -1,    43,    -1,    45,    -1,
    -1,    -1,    49,    -1,    51,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    13,    14
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 54 "parser.y"
{
        print_ast(yyvsp[0].ast, 0);
    ;
    break;}
case 2:
#line 57 "parser.y"
{
        yyerror("Could not parse input");
    ;
    break;}
case 3:
#line 63 "parser.y"
{ yyval.ast = make_node("CODE", 2, yyvsp[-1].ast, yyvsp[0].ast); ;
    break;}
case 4:
#line 64 "parser.y"
{ yyval.ast = make_node("CODE", 1, yyvsp[0].ast); ;
    break;}
case 5:
#line 67 "parser.y"
{
        current_param_index = 0;
        if (symbol_exists_in_current_scope(yyvsp[-6].sval)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Function '%s' already defined in this block", yyvsp[-6].sval);
            yyerror(error_msg);
        } else {
            DataType param_types[MAX_PARAMS];
            int param_count = count_params(yyvsp[-4].ast);
            collect_param_types(yyvsp[-4].ast, param_types);
            insert_function_with_param_types(yyvsp[-6].sval, get_type_from_name(yyvsp[0].ast->name), param_count, param_types);
            printf("Pre-registered function '%s' in scope %d with %d params\n", yyvsp[-6].sval, current_scope, param_count);
        }
        // In each function declaration rule
        strcpy(current_function_name, yyvsp[-6].sval);

        if (strcmp(yyvsp[-6].sval, "_main_") == 0) {
            if (main_defined)
                yyerror("Semantic Error: Multiple definitions of _main_ function");
            main_defined = 1;
            inside_main = 1;

            if (yyvsp[-4].ast->child_count > 0 && strcmp(yyvsp[-4].ast->children[0]->name, "NONE") != 0)
                yyerror("Semantic Error: _main_ function cannot take arguments");

            if (get_type_from_name(yyvsp[0].ast->name) != DT_VOID)
                yyerror("Semantic Error: _main_ function cannot return a value");
        }
        // Add this check in the function declaration rule actions
        if (get_type_from_name(yyvsp[0].ast->name) == DT_STRING) {
            yyerror("Semantic Error: Function cannot return string type");
        }
    ;
    break;}
case 6:
#line 99 "parser.y"
{
        inside_main = 0;
        yyval.ast = make_node("FUNCTION", 4,
             make_node(yyvsp[-8].sval, 0),
             yyvsp[-6].ast,
             make_node("RET", 1, yyvsp[-2].ast),
             make_node("BODY", 1, yyvsp[0].ast));
             // At the end of each function rule, after creating the AST node
current_function_name[0] = '\0';  // Clear the current function name
    ;
    break;}
case 7:
#line 110 "parser.y"
{
        if (symbol_exists_in_current_scope(yyvsp[-5].sval)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Function '%s' already defined in this block", yyvsp[-5].sval);
            yyerror(error_msg);
        } else {
            DataType param_types[MAX_PARAMS];  // במקרה זה, אין פרמטרים
            insert_function_with_param_types(yyvsp[-5].sval, get_type_from_name(yyvsp[0].ast->name), 0, param_types);
            printf("Pre-registered function '%s' in scope %d with 0 params\n", yyvsp[-5].sval, current_scope);
        }
        // In each function declaration rule
        strcpy(current_function_name, yyvsp[-5].sval);

        if (strcmp(yyvsp[-5].sval, "_main_") == 0) {
            if (main_defined)
                yyerror("Semantic Error: Multiple definitions of _main_ function");
            main_defined = 1;
            inside_main = 1;

            if (get_type_from_name(yyvsp[0].ast->name) != DT_VOID)
                yyerror("Semantic Error: _main_ function cannot return a value");
        }
        if (get_type_from_name(yyvsp[0].ast->name) == DT_STRING) {
            yyerror("Semantic Error: Function cannot return string type");
        }
    ;
    break;}
case 8:
#line 135 "parser.y"
{
        inside_main = 0;
        yyval.ast = make_node("FUNCTION", 4,
             make_node(yyvsp[-7].sval, 0),
             make_node("ARGS", 1, make_node("NONE", 0)),
             make_node("RET", 1, yyvsp[-2].ast),
             make_node("BODY", 1, yyvsp[0].ast));
             // At the end of each function rule, after creating the AST node
current_function_name[0] = '\0';  // Clear the current function name
    ;
    break;}
case 9:
#line 146 "parser.y"
{
    current_param_index = 0;
        if (symbol_exists_in_current_scope(yyvsp[-4].sval)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Function '%s' already defined in this block", yyvsp[-4].sval);
            yyerror(error_msg);
        } else {
            DataType param_types[MAX_PARAMS];
            int param_count = count_params(yyvsp[-2].ast);
            collect_param_types(yyvsp[-2].ast, param_types);
            insert_function_with_param_types(yyvsp[-4].sval, DT_VOID, param_count, param_types);
            printf("Pre-registered function '%s' in scope %d with %d params\n", yyvsp[-4].sval, current_scope, param_count);
        }
        // In each function declaration rule
        strcpy(current_function_name, yyvsp[-4].sval);

        if (strcmp(yyvsp[-4].sval, "_main_") == 0) {
            if (main_defined)
                yyerror("Semantic Error: Multiple definitions of _main_ function");
            main_defined = 1;
            inside_main = 1;

            if (yyvsp[-2].ast->child_count > 0 && strcmp(yyvsp[-2].ast->children[0]->name, "NONE") != 0)
                yyerror("Semantic Error: _main_ function cannot take arguments");
        }
    ;
    break;}
case 10:
#line 171 "parser.y"
{
        inside_main = 0;
        yyval.ast = make_node("FUNCTION", 4,
             make_node(yyvsp[-6].sval, 0),
             yyvsp[-4].ast,
             make_node("RET", 1, make_node("NONE", 0)),
             make_node("BODY", 1, yyvsp[0].ast));
             // At the end of each function rule, after creating the AST node
current_function_name[0] = '\0';  // Clear the current function name
    ;
    break;}
case 11:
#line 182 "parser.y"
{
        if (symbol_exists_in_current_scope(yyvsp[-3].sval)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Function '%s' already defined in this block", yyvsp[-3].sval);
            yyerror(error_msg);
        } else {
            DataType param_types[MAX_PARAMS];  // במקרה זה, אין פרמטרים
            insert_function_with_param_types(yyvsp[-3].sval, DT_VOID, 0, param_types);
            printf("Pre-registered function '%s' in scope %d with 0 params\n", yyvsp[-3].sval, current_scope);
        }
        // In each function declaration rule
    strcpy(current_function_name, yyvsp[-3].sval);

        if (strcmp(yyvsp[-3].sval, "_main_") == 0) {
            if (main_defined)
                yyerror("Semantic Error: Multiple definitions of _main_ function");
            main_defined = 1;
            inside_main = 1;
        }
    ;
    break;}
case 12:
#line 201 "parser.y"
{
        inside_main = 0;
        yyval.ast = make_node("FUNCTION", 4,
             make_node(yyvsp[-5].sval, 0),
             make_node("ARGS", 1, make_node("NONE", 0)),
             make_node("RET", 1, make_node("NONE", 0)),
             make_node("BODY", 1, yyvsp[0].ast));

             // At the end of each function rule, after creating the AST node
        current_function_name[0] = '\0';  // Clear the current function name
    ;
    break;}
case 13:
#line 215 "parser.y"
{ yyval.ast = make_node("ARGS", 1, yyvsp[0].ast); ;
    break;}
case 14:
#line 216 "parser.y"
{ yyval.ast = make_node("ARGS", 1, make_node("NONE", 0)); ;
    break;}
case 15:
#line 220 "parser.y"
{
        yyval.ast = make_node("", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 16:
#line 223 "parser.y"
{
        yyval.ast = yyvsp[0].ast;
    ;
    break;}
case 17:
#line 230 "parser.y"
{
        // הגדלת המונה
        current_param_index++;
        
        // בדיקת סדר פרמטרים
        check_param_order(yyvsp[-3].sval, current_param_index);
        
        // שאר הקוד נשאר כמו שהוא
        insert_symbol(yyvsp[0].sval, VAR_SYM, get_type_from_name(yyvsp[-2].ast->name));
        printf("  Inserted parameter '%s' as variable in scope %d\n", yyvsp[0].sval, current_scope);
        
        yyval.ast = make_node("", 3, make_node(yyvsp[-3].sval, 0), make_node(yyvsp[-2].ast->name, 0), make_node(yyvsp[0].sval, 0));
    ;
    break;}
case 18:
#line 246 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 19:
#line 247 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 20:
#line 248 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 21:
#line 249 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 22:
#line 250 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 23:
#line 251 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 24:
#line 252 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 25:
#line 253 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 26:
#line 257 "parser.y"
{ 
        printf("DEBUG: Processing stmt_list + stmt, current_scope = %d\n", current_scope);
        yyval.ast = make_node("", 2, yyvsp[-1].ast, yyvsp[0].ast); 
    ;
    break;}
case 27:
#line 261 "parser.y"
{ 
        printf("DEBUG: Processing solo stmt, current_scope = %d\n", current_scope);
        yyval.ast = yyvsp[0].ast; 
    ;
    break;}
case 40:
#line 283 "parser.y"
{
        Symbol* sym = lookup_any_scope(yyvsp[-3].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[-3].sval);
            yyerror(error_msg);
        } else {
            // Check type compatibility
            DataType lhs_type = sym->type;
            DataType rhs_type = get_expr_type(yyvsp[-1].ast);
            
            // Check if null is assigned to a non-pointer type
            if (rhs_type == DT_PTR_INT && yyvsp[-1].ast->name && strcmp(yyvsp[-1].ast->name, "nullptr") == 0) {
                if (lhs_type != DT_PTR_INT && lhs_type != DT_PTR_CHAR && lhs_type != DT_PTR_REAL) {
                    char error_msg[100];
                    sprintf(error_msg, "Semantic Error: Cannot assign null to non-pointer type %s", 
                            get_name_from_type(lhs_type));
                    yyerror(error_msg);
                }
            }
            // Check general type compatibility
            else if (!is_type_compatible(lhs_type, rhs_type)) {
                char error_msg[100];
                sprintf(error_msg, "Semantic Error: Type mismatch in assignment, cannot assign %s to %s", 
                        get_name_from_type(rhs_type), get_name_from_type(lhs_type));
                yyerror(error_msg);
            }
        }
        yyval.ast = make_node("=", 2, make_node(yyvsp[-3].sval, 0), yyvsp[-1].ast);
    ;
    break;}
case 41:
#line 313 "parser.y"
{
        // Check that the variable is a string
        Symbol* sym = lookup_any_scope(yyvsp[-6].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[-6].sval);
            yyerror(error_msg);
        } else if (sym->type != DT_STRING) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: [] operator can only be used with string type, '%s' is of type %s", 
                    yyvsp[-6].sval, get_name_from_type(sym->type));
            yyerror(error_msg);
        } else {
            // Check that the index is an integer
            check_string_index(yyvsp[-4].ast);
            
            // Check that the assigned value is a char
            DataType rhs_type = get_expr_type(yyvsp[-1].ast);
            if (rhs_type != DT_CHAR) {
                char error_msg[100];
                sprintf(error_msg, "Semantic Error: String element can only be assigned a char value, got %s", 
                        get_name_from_type(rhs_type));
                yyerror(error_msg);
            }
        }
        yyval.ast = make_node("=", 2, make_node("array_access", 2, make_node(yyvsp[-6].sval, 0), yyvsp[-4].ast), yyvsp[-1].ast);
    ;
    break;}
case 42:
#line 340 "parser.y"
{
        Symbol* sym = lookup_any_scope(yyvsp[-3].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[-3].sval);
            yyerror(error_msg);
        }
        
        // בדיקה סמנטית - האם המשתנה הוא מצביע
        DataType type = sym->type;
        if (!is_pointer_type(type)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Cannot dereference non-pointer variable '%s'", yyvsp[-3].sval);
            yyerror(error_msg);
        }
        
        // מציאת הטיפוס שהמצביע מצביע אליו
        DataType target_type = get_base_type(type);
        
        // בדיקת התאמת טיפוסים בהשמה
        DataType expr_type = get_expr_type(yyvsp[-1].ast);
        if (target_type != expr_type) {
            // בדיקת המרה אפשרית מ-INT ל-REAL
            if (!(target_type == DT_REAL && expr_type == DT_INT)) {
                char error_msg[100];
                sprintf(error_msg, "Semantic Error: Type mismatch in assignment to dereferenced pointer: expected %s, got %s",
                        get_name_from_type(target_type), get_name_from_type(expr_type));
                yyerror(error_msg);
            }
        }
        
        yyval.ast = make_node("=", 2, make_node("*", 1, make_node(yyvsp[-3].sval, 0)), yyvsp[-1].ast);
    ;
    break;}
case 43:
#line 376 "parser.y"
{
        yyval.ast = make_node("VAR", 2, yyvsp[-1].ast, yyvsp[0].ast);
    ;
    break;}
case 44:
#line 379 "parser.y"
{
        yyval.ast = make_node("VAR", 2, yyvsp[-1].ast, yyvsp[0].ast);
    ;
    break;}
case 45:
#line 384 "parser.y"
{
        yyval.ast = make_node("DECLS", 2, yyvsp[-1].ast, yyvsp[0].ast);
    ;
    break;}
case 46:
#line 387 "parser.y"
{
        yyval.ast = yyvsp[0].ast;
    ;
    break;}
case 47:
#line 392 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_INT);
        yyval.ast = make_node("TYPE", 2, make_node("int", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 48:
#line 396 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_BOOL);
        yyval.ast = make_node("TYPE", 2, make_node("bool", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 49:
#line 400 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_CHAR);
        yyval.ast = make_node("TYPE", 2, make_node("char", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 50:
#line 404 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_STRING);
        yyval.ast = make_node("TYPE", 2, make_node("string", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 51:
#line 408 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_REAL);
        yyval.ast = make_node("TYPE", 2, make_node("real", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 52:
#line 412 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_REAL);
        yyval.ast = make_node("TYPE", 2, make_node("real", 0), make_node(yyvsp[-3].sval, 1,make_node(yyvsp[-1].sval,0)));
    ;
    break;}
case 53:
#line 416 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_INT);
        yyval.ast = make_node("TYPE", 2, make_node("int", 0), make_node(yyvsp[-3].sval, 1, make_node(yyvsp[-1].sval, 0)));
    ;
    break;}
case 54:
#line 420 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_CHAR);
        yyval.ast = make_node("TYPE", 2, make_node("char", 0), make_node(yyvsp[-3].sval, 1, make_node(yyvsp[-1].sval, 0)));
    ;
    break;}
case 55:
#line 424 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_STRING);
        yyval.ast = make_node("TYPE", 2, make_node("string", 0), make_node(yyvsp[-3].sval, 1, make_node(yyvsp[-1].sval, 0)));
    ;
    break;}
case 56:
#line 428 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_BOOL);
        yyval.ast = make_node("TYPE", 2, make_node("bool", 0), make_node(yyvsp[-3].sval, 1, make_node("true", 0)));
    ;
    break;}
case 57:
#line 432 "parser.y"
{
        insert_checked_variable(yyvsp[-3].sval, DT_BOOL);
        yyval.ast = make_node("TYPE", 2, make_node("bool", 0), make_node(yyvsp[-3].sval, 1, make_node("false", 0)));
    ;
    break;}
case 58:
#line 436 "parser.y"
{
        int size = atoi(yyvsp[-2].sval);
        if (size <= 0) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: String size must be a positive integer");
            yyerror(error_msg);
        }
        insert_checked_variable(yyvsp[-4].sval, DT_STRING);
        yyval.ast = make_node("TYPE", 3, make_node("string", 0), make_node(yyvsp[-4].sval, 0), make_node(yyvsp[-2].sval, 0));
    ;
    break;}
case 59:
#line 446 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_PTR_INT);
        yyval.ast = make_node("TYPE", 2, make_node("int*", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 60:
#line 450 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_PTR_CHAR);
        yyval.ast = make_node("TYPE", 2, make_node("char*", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 61:
#line 454 "parser.y"
{
        insert_checked_variable(yyvsp[-1].sval, DT_PTR_REAL);
        yyval.ast = make_node("TYPE", 2, make_node("real*", 0), make_node(yyvsp[-1].sval, 0));
    ;
    break;}
case 62:
#line 462 "parser.y"
{
        printf("DEBUG: Processing return with value in function '%s'\n", current_function_name);
        if (inside_main) {
            yyerror("Semantic Error: _main_ function cannot return a value");
        }
        
        // Check if return type matches function declaration
        check_return_type(yyvsp[-1].ast, current_function_name);
        
        yyval.ast = make_node("RETURN", 1, yyvsp[-1].ast);
    ;
    break;}
case 63:
#line 473 "parser.y"
{
        printf("DEBUG: Processing empty return in function '%s'\n", current_function_name);
        
        // Empty return is equivalent to "return void"
        check_return_type(make_node("NONE", 0), current_function_name);
        
        yyval.ast = make_node("RETURN", 1, make_node("NONE", 0));
    ;
    break;}
case 64:
#line 485 "parser.y"
{
        check_boolean_condition(yyvsp[-5].ast, "if");
        yyval.ast = make_node("IF-ELSE", 3, yyvsp[-5].ast, yyvsp[-3].ast, yyvsp[0].ast);
    ;
    break;}
case 65:
#line 490 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "if");
        yyval.ast = make_node("IF", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 66:
#line 495 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "if");
        yyval.ast = make_node("IF", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 67:
#line 500 "parser.y"
{
        check_boolean_condition(yyvsp[-5].ast, "if");
        yyval.ast = make_node("IF-ELSE", 3, yyvsp[-5].ast, yyvsp[-3].ast, yyvsp[0].ast);
    ;
    break;}
case 68:
#line 505 "parser.y"
{
        check_boolean_condition(yyvsp[-6].ast, "if");
        yyval.ast = make_node("IF-ELIF-ELSE", 4, yyvsp[-6].ast, yyvsp[-4].ast, yyvsp[-3].ast, yyvsp[0].ast);
    ;
    break;}
case 69:
#line 514 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "elif");
        yyval.ast = make_node("ELIF", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 70:
#line 519 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "elif");
        yyval.ast = make_node("ELIF - ...", 3, yyvsp[-4].ast, make_node("elif", 2, yyvsp[-2].ast, yyvsp[0].ast));
    ;
    break;}
case 71:
#line 526 "parser.y"
{
        check_boolean_condition(yyvsp[-1].ast, "while");
        yyval.ast = make_node("while", 1, yyvsp[-1].ast);
    ;
    break;}
case 72:
#line 531 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "while");
        yyval.ast = make_node("while2", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 73:
#line 536 "parser.y"
{
        check_boolean_condition(yyvsp[-2].ast, "while");
        yyval.ast = make_node("while2", 2, yyvsp[-2].ast, yyvsp[0].ast);
    ;
    break;}
case 74:
#line 542 "parser.y"
{
        check_boolean_condition(yyvsp[-1].ast, "do-while");
        yyval.ast = make_node("do-while", 2, yyvsp[-3].ast, yyvsp[-1].ast);
    ;
    break;}
case 75:
#line 547 "parser.y"
{
        check_boolean_condition(yyvsp[-1].ast, "do-while");
        yyval.ast = make_node("do-while", 2, yyvsp[-3].ast, yyvsp[-1].ast);
    ;
    break;}
case 76:
#line 552 "parser.y"
{
        check_boolean_condition(yyvsp[-1].ast, "do-while");
        yyval.ast = make_node("do-while", 2, yyvsp[-3].ast, yyvsp[-1].ast);
    ;
    break;}
case 77:
#line 559 "parser.y"
{
        check_boolean_condition(yyvsp[-5].ast, "for"); // Check the loop condition expression is boolean
        yyval.ast = make_node("for", 4, yyvsp[-6].ast, yyvsp[-5].ast, yyvsp[-3].ast, yyvsp[0].ast);
    ;
    break;}
case 78:
#line 564 "parser.y"
{
        check_boolean_condition(yyvsp[-5].ast, "for"); // Check the loop condition expression is boolean
        yyval.ast = make_node("for", 4, yyvsp[-6].ast, yyvsp[-5].ast, yyvsp[-3].ast, yyvsp[0].ast);
    ;
    break;}
case 79:
#line 571 "parser.y"
{
        yyval.ast = make_node("=", 2, make_node(yyvsp[-2].sval, 0), yyvsp[0].ast);
    ;
    break;}
case 80:
#line 574 "parser.y"
{
        yyval.ast = yyvsp[0].ast;
    ;
    break;}
case 81:
#line 579 "parser.y"
{ yyval.ast = make_node("args", 1, yyvsp[0].ast); ;
    break;}
case 82:
#line 580 "parser.y"
{ yyval.ast = make_node("args", 1, make_node("none", 0)); ;
    break;}
case 83:
#line 585 "parser.y"
{
        yyval.ast= make_node ("par",2,yyvsp[-2].ast,yyvsp[0].ast);
    ;
    break;}
case 84:
#line 589 "parser.y"
{
          yyval.ast= make_node ("par",1,yyvsp[0].ast);
    ;
    break;}
case 85:
#line 596 "parser.y"
{
        Symbol* func = lookup_any_scope(yyvsp[-4].sval);
        if (!func) {
            char msg[100];
            sprintf(msg, "Semantic Error: Function '%s' called before declaration", yyvsp[-4].sval);
            yyerror(msg);
        } else if (func->kind != FUNC_SYM) {
            char msg[100];
            sprintf(msg, "Semantic Error: '%s' is not a function", yyvsp[-4].sval);
            yyerror(msg);
        } else {
            int expected = func->param_count;
            int actual = count_actual_params(yyvsp[-2].ast);
            if (expected != actual) {
                char msg[150];
                sprintf(msg, "Semantic Error: Function '%s' expects %d arguments, got %d", yyvsp[-4].sval, expected, actual);
                yyerror(msg);
            } else {
                // בדיקת טיפוסי פרמטרים
                check_param_types(yyvsp[-4].sval, yyvsp[-2].ast);
            }
        }

        yyval.ast = make_node("ASSIGN-CALL", 2,
                       make_node(yyvsp[-7].sval, 0),
                       make_node("CALL", 2, make_node(yyvsp[-4].sval, 0), yyvsp[-2].ast));
    ;
    break;}
case 86:
#line 626 "parser.y"
{
        Symbol* func = lookup_any_scope(yyvsp[-4].sval);
        if (!func) {
            char msg[100];
            sprintf(msg, "Semantic Error: Function '%s' called before declaration", yyvsp[-4].sval);
            yyerror(msg);
        } else if (func->kind != FUNC_SYM) {
            char msg[100];
            sprintf(msg, "Semantic Error: '%s' is not a function", yyvsp[-4].sval);
            yyerror(msg);
        } else {
            int expected = func->param_count;
            int actual = count_actual_params(yyvsp[-2].ast);
            if (expected != actual) {
                char msg[150];
                sprintf(msg, "Semantic Error: Function '%s' expects %d arguments, got %d", yyvsp[-4].sval, expected, actual);
                yyerror(msg);
            } else {
                // בדיקת טיפוסי פרמטרים
                check_param_types(yyvsp[-4].sval, yyvsp[-2].ast);
            }
        }

        yyval.ast = make_node("CALL", 2, make_node(yyvsp[-4].sval, 0), yyvsp[-2].ast);
    ;
    break;}
case 87:
#line 654 "parser.y"
{
        enter_scope();
    ;
    break;}
case 88:
#line 657 "parser.y"
{
        yyval.ast = make_node("BLOCK", 1, yyvsp[-1].ast); 
        exit_scope();
    ;
    break;}
case 89:
#line 661 "parser.y"
{
        enter_scope();
    ;
    break;}
case 90:
#line 664 "parser.y"
{
        yyval.ast = make_node("BLOCK", 0); 
        exit_scope();
     ;
    break;}
case 91:
#line 671 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '+' operator requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("+", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 92:
#line 682 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '-' operator requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("-", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 93:
#line 693 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '*' operator requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("*", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 94:
#line 704 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '/' operator requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("/", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 95:
#line 715 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (left != right) {
        char msg[200];
        sprintf(msg, "Semantic Error: '==' requires operands of same type, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("==", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 96:
#line 726 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (left != right) {
        char msg[200];
        sprintf(msg, "Semantic Error: '!=' requires operands of same type, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("!=", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 97:
#line 737 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '<' requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("<", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 98:
#line 748 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '>' requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node(">", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 99:
#line 759 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '<=' requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node("<=", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 100:
#line 770 "parser.y"
{
    DataType left = get_expr_type(yyvsp[-2].ast);
    DataType right = get_expr_type(yyvsp[0].ast);
    if (!((left == DT_INT || left == DT_REAL) && (right == DT_INT || right == DT_REAL))) {
        char msg[200];
        sprintf(msg, "Semantic Error: '>=' requires numeric types, got '%s' and '%s'",
                get_name_from_type(left), get_name_from_type(right));
        yyerror(msg);
    }
    yyval.ast = make_node(">=", 2, yyvsp[-2].ast, yyvsp[0].ast);
	;
    break;}
case 101:
#line 781 "parser.y"
{ yyval.ast = yyvsp[-1].ast; ;
    break;}
case 102:
#line 784 "parser.y"
{
        // Check that the variable is a string
        Symbol* sym = lookup_any_scope(yyvsp[-3].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[-3].sval);
            yyerror(error_msg);
        } else if (sym->type != DT_STRING) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: [] operator can only be used with string type, '%s' is of type %s", 
                    yyvsp[-3].sval, get_name_from_type(sym->type));
            yyerror(error_msg);
        } else {
            // Check that the index is an integer
            check_string_index(yyvsp[-1].ast);
        }
        yyval.ast = make_node("array_access", 2, make_node(yyvsp[-3].sval, 0), yyvsp[-1].ast);
    ;
    break;}
case 103:
#line 804 "parser.y"
{
        // This rule should not be used for array access
        char error_msg[100];
        sprintf(error_msg, "Semantic Error: Invalid use of [] operator");
        yyerror(error_msg);
        yyval.ast = yyvsp[-1].ast; // Fallback to avoid further errors
    ;
    break;}
case 104:
#line 812 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 105:
#line 813 "parser.y"
{
        Symbol* sym = lookup_any_scope(yyvsp[0].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[0].sval);
            yyerror(error_msg);
        }
        yyval.ast = make_node(yyvsp[0].sval, 0);
    ;
    break;}
case 106:
#line 822 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 107:
#line 823 "parser.y"
{ yyval.ast = make_node(yyvsp[0].sval, 0); ;
    break;}
case 108:
#line 824 "parser.y"
{ yyval.ast = make_node("nullptr", 0); ;
    break;}
case 109:
#line 825 "parser.y"
{ yyval.ast = make_node("true", 0); ;
    break;}
case 110:
#line 826 "parser.y"
{ yyval.ast = make_node("false", 0); ;
    break;}
case 111:
#line 827 "parser.y"
{ yyval.ast = make_node("and", 0); ;
    break;}
case 112:
#line 828 "parser.y"
{ yyval.ast = make_node("or", 0); ;
    break;}
case 113:
#line 829 "parser.y"
{ yyval.ast = make_node("not", 0); ;
    break;}
case 114:
#line 830 "parser.y"
{
        Symbol* func = lookup_any_scope(yyvsp[-3].sval);
        if (func && func->kind == FUNC_SYM) {
            int expected = func->param_count;
            int actual = count_actual_params(yyvsp[-1].ast);
            if (expected == actual) {
                // בדיקת טיפוסי פרמטרים
                check_param_types(yyvsp[-3].sval, yyvsp[-1].ast);
            }
        }
        yyval.ast = make_node("call", 2, make_node(yyvsp[-3].sval, 0), yyvsp[-1].ast);
    ;
    break;}
case 115:
#line 842 "parser.y"
{
        Symbol* func = lookup_any_scope(yyvsp[-3].sval);
        if (func && func->kind == FUNC_SYM) {
            int expected = func->param_count;
            int actual = count_actual_params(yyvsp[-1].ast);
            if (expected == actual) {
                // בדיקת טיפוסי פרמטרים
                check_param_types(yyvsp[-3].sval, yyvsp[-1].ast);
            }
        }
        yyval.ast = make_node("call", 2, make_node(yyvsp[-3].sval, 0), yyvsp[-1].ast);
    ;
    break;}
case 116:
#line 854 "parser.y"
{ yyval.ast = make_node("and", 2, yyvsp[-2].ast, yyvsp[0].ast); ;
    break;}
case 117:
#line 855 "parser.y"
{ yyval.ast = make_node("or", 2, yyvsp[-2].ast, yyvsp[0].ast); ;
    break;}
case 118:
#line 856 "parser.y"
{ yyval.ast = make_node("not", 1, yyvsp[0].ast); ;
    break;}
case 119:
#line 859 "parser.y"
{
        Symbol* sym = lookup_any_scope(yyvsp[0].sval);
        if (!sym) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[0].sval);
            yyerror(error_msg);
        }
        
        // בדיקה סמנטית - האם המשתנה הוא מצביע
        DataType type = sym->type;
        if (!is_pointer_type(type)) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Cannot dereference non-pointer variable '%s'", yyvsp[0].sval);
            yyerror(error_msg);
        }
        
        yyval.ast = make_node("*", 1, make_node(yyvsp[0].sval, 0));
    ;
    break;}
case 120:
#line 877 "parser.y"
{
    Symbol* sym = lookup_any_scope(yyvsp[0].sval);
    if (!sym) {
        char error_msg[100];
        sprintf(error_msg, "Semantic Error: Variable '%s' used before declaration", yyvsp[0].sval);
        yyerror(error_msg);
    } else {
        // נבדוק שהטיפוס בסיסי ולא מצביע
        DataType type = sym->type;
        if (type == DT_PTR_INT || type == DT_PTR_CHAR || type == DT_PTR_REAL) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Cannot take address of pointer variable '%s'", yyvsp[0].sval);
            yyerror(error_msg);
        } else if (type != DT_INT && type != DT_REAL && type != DT_CHAR && type != DT_STRING) {
            char error_msg[100];
            sprintf(error_msg, "Semantic Error: Cannot take address of '%s' with type '%s'",
                    yyvsp[0].sval, get_name_from_type(type));
            yyerror(error_msg);
        }
    }

    yyval.ast = make_node("&", 1, make_node(yyvsp[0].sval, 0));
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 903 "parser.y"


void yyerror(const char* s) {
    fprintf(stderr, "Syntax Error: %s\n", s);
}

int main(int argc, char* argv[]) {
    printf("DEBUG: Starting compiler\n");

    enter_scope();
    int result = yyparse();

    printf("\nDEBUG: Final symbol tables:\n");
    print_symbol_tables();
    preserve_symbol_tables = 1;
    exit_scope();

    if (!main_defined) {
        yyerror("Semantic Error: No _main_ function defined");
    }

    return result;
}
